/* global
  WEBPACK_VARIABLE_API_SERVER,
  WEBPACK_VARIABLE_STRIPE_PUBLIC_KEY,
  WEBPACK_VARIABLE_SEGMENT_API_KEY,
*/

export default {
  API_SERVER: WEBPACK_VARIABLE_API_SERVER,
  STRIPE_PUBLIC_KEY: WEBPACK_VARIABLE_STRIPE_PUBLIC_KEY,
  SEGMENT_API_KEY: WEBPACK_VARIABLE_SEGMENT_API_KEY
}
